<div class="row">
    <div class="span4">
        <section class="block">
            <h2>
                Latest Movies
            </h2>

            <ul class="media-lineitems">

<?php foreach ($this->newMovies as $movie): ?>

                <li>
                    <a href="/movies/<?php echo $movie['id']; ?>/<?php echo Helper_String::toLink($movie['title']); ?>/" title="<?php echo $movie['title']; ?>">
                        <img src="<?php echo $this->conf->cdn->movieimg; ?><?php echo $movie['id']; ?>.gif" alt="<?php echo $movie['title']; ?>" />
                        <strong><?php echo $movie['title']; ?></strong>
                    </a>
                </li>

<?php endforeach; ?>

            </ul>
        </section>
    </div>

    <div class="span4">
        <section class="block">
            <h2>
                Popular Movies
            </h2>

            <ul class="media-lineitems">

<?php foreach ($this->popularMovies as $movie): ?>

                <li>
                    <a href="/movies/<?php echo $movie['id']; ?>/<?php echo Helper_String::toLink($movie['title']); ?>/" title="<?php echo $movie['title']; ?>">
                        <img src="<?php echo $this->conf->cdn->movieimg; ?><?php echo $movie['id']; ?>.gif" alt="<?php echo $movie['title']; ?>" />
                        <strong><?php echo $movie['title']; ?></strong>
                    </a>
                </li>

<?php endforeach; ?>

            </ul>
        </section>
    </div>

    <div class="span4">
        <section class="block">
            <h2>
                Best Movies
            </h2>

            <ul class="media-lineitems">
<?php foreach ($this->bestMovies as $movie): ?>

                <li>
                    <a href="/movies/<?php echo $movie['id']; ?>/<?php echo Helper_String::toLink($movie['title']); ?>/" title="<?php echo $movie['title']; ?>">
                        <img src="<?php echo $this->conf->cdn->movieimg; ?><?php echo $movie['id']; ?>.gif" alt="<?php echo $movie['title']; ?>" />
                        <strong><?php echo $movie['title']; ?></strong>
                    </a>
                </li>

<?php endforeach; ?>

            </ul>
        </section>
    </div>
</div>
