<div class="left content-block" style="width: 309px; margin-right: 1.333em;">
    <div class="block-header">
        Latest Movies
    </div>

    <div class="padding-links">

<?php foreach ($this->newMovies as $movie): ?>

        <a href="/movies/<?php echo $movie['id']; ?>/<?php echo Helper_String::toLink($movie['title']); ?>/" title="<?php echo $movie['title']; ?>">
            <img src="<?php echo $this->conf->cdn->movieimg; ?><?php echo $movie['id']; ?>.gif" alt="<?php echo $movie['title']; ?>" class="text-img" />
            <strong><?php echo $movie['title']; ?></strong>
        </a>

<?php endforeach; ?>
        
    </div>
</div>

<div class="left content-block" style="width: 310px; margin-right: 1.333em;">
    <div class="block-header">
        Popular Movies
    </div>

    <div class="padding-links">

<?php foreach ($this->popularMovies as $movie): ?>

        <a href="/movies/<?php echo $movie['id']; ?>/<?php echo Helper_String::toLink($movie['title']); ?>/" title="<?php echo $movie['title']; ?>">
            <img src="<?php echo $this->conf->cdn->movieimg; ?><?php echo $movie['id']; ?>.gif" alt="<?php echo $movie['title']; ?>" class="text-img" />
            <strong><?php echo $movie['title']; ?></strong>
        </a>

<?php endforeach; ?>

    </div>
</div>

<div class="left content-block" style="width: 309px;">
    <div class="block-header">
        Best Movies
    </div>

    <div class="padding-links">

<?php foreach ($this->bestMovies as $movie): ?>

        <a href="/movies/<?php echo $movie['id']; ?>/<?php echo Helper_String::toLink($movie['title']); ?>/" title="<?php echo $movie['title']; ?>">
            <img src="<?php echo $this->conf->cdn->movieimg; ?><?php echo $movie['id']; ?>.gif" alt="<?php echo $movie['title']; ?>" class="text-img" />
            <strong><?php echo $movie['title']; ?></strong>
        </a>

<?php endforeach; ?>

    </div>
</div>