<div class="content-span">
    <div class="content-block">
        <div class="block-header">
            <a href="/community" title="Return to Community Forums">
                Community
            </a>

            &nbsp;&raquo;&nbsp;
            <a href="/community/forum/<?php echo $this->topicInfo['forumId']; ?>" title="Return to <?php echo $this->topicInfo['forumName']; ?> Forum">
                <?php echo $this->topicInfo['forumName']; ?>
            </a>

            &nbsp;&raquo;&nbsp;
            <a href="<?php echo $this->url(array('page' => 1)); ?>" title="<?php echo ($this->topicInfo['page'] != 1 ? 'Return to Page 1 of Topic' : 'Refresh Topic'); ?>">
                <em><?php echo $this->topicInfo['topicName']; ?></em>
            </a>

<?php if ($this->topicInfo['page'] != 1): ?>

            &nbsp;&raquo;&nbsp;
            <a href="<?php echo $this->url(); ?>" title="Refresh Page">
                Page <?php echo $this->topicInfo['page']; ?>
            </a>

<?php endif; ?>
        
        </div>

<?php foreach ($this->threads as $thread): ?>

        <div class="padding-content" style="border-bottom: 1px solid #ddd;">
            <?php echo $thread['post']; ?>
        </div>

        <div class="padding-content text-disabled">
            <a href="http://<?php echo $thread['link_name']; ?>.<?php echo $this->siteDomain; ?>" title="View Profile" style="border-bottom: none; line-height: 0;">
                <img src="/media/profiles/avatars/<?php echo $thread['id_user']; ?>.gif" alt="Icon" class="text-img" />
                <?php echo $thread['nick_name']; ?>
            </a> on <?php echo $thread['date']; ?>
        </div>
    </div>
    <div class="content-block">
    
<?php endforeach; ?>

        <?php echo $this->paginator; ?>
    </div>
</div>