<div class="row">
    <div class="span6">
        <section class="block">
            <h2>
                Sign In
            </h2>

            <div>
                <?php echo $this->form; ?>
            </div>
        </section>
    </div>

    <div class="span6">
        <section class="block">
            <h2>
                Create Account
            </h2>

            <article>
                This feature is not yet available.
            </article>
        </section>

        <section class="block">
            <h2>
                Request Forgotten Password
            </h2>

            <article>
                This feature is not yet available.
            </article>
        </section>
    </div>
</div>
