<div class="content-block left" style="width: 472px;">
    <div class="block-header">
        Sign In
    </div>

    <div class="">
        <?php echo $this->form; ?>
    </div>
</div>

<div class="content-block right" style="width: 472px;">
    <div class="block-header">
        Create Account
    </div>

    <div class="padding-content">
        This feature is not yet available.
    </div>
</div>

<div class="content-block right" style="width: 472px;">

    <div class="block-header">
        Request Forgotten Password
    </div>

    <div class="padding-content">
        This feature is not yet available.
    </div>
</div>
