<section class="block">
    <h2>
        Browse the Community Forums!
    </h2>

    <ul class="media-halflinks">

<?php foreach ($this->forums as $row): ?>

        <li>
            <a href="/community/forum/<?php echo $row['id']; ?>" title="<?php echo $row['name']; ?>">
                <h3><?php echo $row['name']; ?></h3>
                <span>
                    <?php echo $row['description']; ?>
                </span>
            </a>
        </li>

<?php endforeach; ?>

    </ul>
</section>
