<div class="main">
  <div class="dft-top">
    <div class="dft-hdr dft-ldr">
      Copyright Notice</div>
                
    <div class="dft-cnt">
      To file a copyright infringement notification with us, you will need to send an email to copyright@txm.com that includes substantially the following (please consult your legal counsel or see Section 512(c)(3) of the Copyright Act to confirm these requirements):<br /><br />
      <ol>   
        <li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
        <li>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site.</li>
        <li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit the service provider to locate the material. Providing URLs in the body of an email is the best way to help us locate content quickly.</li>
        <li>Information reasonably sufficient to permit the service provider to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted.</li>
        <li>A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.</li>
        <li>A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
      </ol><br />
      
      Please also note that under Section 512(f) any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability.<br />
      <br />
      If there are many media to be removed, or you expect to have an ongoing need to remove potentially infringing content from TXM.com, we suggest that you sign up for our Content Verification Program, which electronically notifies us, removing any room for error, and significantly increases the speed at which we are able to remove any infringing content.<br />
      Counter-Notification<br />
      <br />
      If you elect to send us a counter notice, please go to our Help Center to access the instructions.<br />
      <br />
      Please note that under Section 512(f) of the Copyright Act, any person who knowingly materially misrepresents that material or activity was removed or disabled by mistake or misidentification may be subject to liability. Please also be advised that we enforce a policy that provides for the termination in appropriate circumstances of subscribers who are repeat infringers.<br />
    </div>
  </div>
</div>