<div class="main">
  <div class="dft-top">
    <div class="dft-hdr dft-ldr">
      Privacy Policy</div>

    <div class="dft-cnt">
      The TXM.com Privacy Policy describes how TXM.com and its subsidiaries treat personal information when you use TXM.com services, including information provided when you use TXM.com. In addition, the following describes privacy practices specific to TXM.com. To understand how we treat the information you give us as you use TXM.com, you should read this policy and the TXM.com Privacy Policy.<br />
      Personal Information<br />
      <br />
          <ul><li>Non-Account Activity. You can watch videos on TXM.com without having a TXM.com Account or a TXM.com Account. You can also contact us about a particular video without having a TXM.com Account or a TXM.com Account.<br />
          </li><li>Account-Related Activity. Certain other activities on TXM.com—like uploading videos, posting comments, flagging videos, or watching restricted videos—require you to have a TXM.com Account or a TXM.com Account. We ask for some personal information when you create a TXM.com Account or a TXM.com Account, including your email address and a password, which is used to protect your account from unauthorized access. A TXM.com Account allows you to access many of our services that require registration.<br />
          </li><li>Usage Information. We may record information about your usage, such as when you use TXM.com, the channels, groups, and favorites you subscribe to, the contacts you communicate with, the videos you watch, and the frequency and size of data transfers, as well as information you display or click on in TXM.com (including UI elements, settings, and other information). If you are logged in, we may associate that information with your account. We may use clear GIFs (a.k.a. "Web Beacons") in HTML-based emails sent to our users to track which emails are opened by recipients.<br />
          </li><li>Content Uploaded to Site. Any personal information or video content that you voluntarily disclose online (on discussion boards, in messages and chat areas, within your playback or profile pages, etc.) becomes publicly available and can be collected and used by others.<br />
          </li></ul>
    </div>

    <div class="dft-hdr grn-bdr">
      Uses</div>
      
    <div class="dft-cnt">
          <ul><li>If you submit personally identifiable information to us through the TXM.com Sites, we use your personal information to operate, maintain, and provide to you the general and personalized features and functionality of the TXM.com Sites, and to process any flagging activity or correspondence you send to us.<br />
          </li><li>Your account name (not your email address) is displayed to other Users when you upload videos or send messages through the TXM.com Sites and other Users can contact you through messages and comments. Any videos that you submit to the TXM.com Sites may be redistributed through the internet and other media channels, and may be viewed by the general public. If you have enabled Active Sharing, other users may see that you, as identified by your account name (not your email address), are watching the same video.<br />
          </li><li>We do not use your email address or other personally identifiable information to send commercial or marketing messages without your consent or except as part of a specific program or feature for which you will have the ability to opt-in or opt-out. We may, however, use your email address without further consent for non-marketing or administrative purposes (such as notifying you of major TXM.com Site changes or for customer service purposes).<br />
          </li><li>We use both your personally identifiable information and certain non-personally-identifiable information (such as anonymous user usage data, cookies, IP addresses, browser type, clickstream data, etc.) to improve the quality and design of the TXM.com Sites and to create new features, promotions, functionality, and services by storing, tracking, analyzing, and processing user preferences and trends, as well as user activity and communications.<br />
          </li><li>We use cookies, clear gifs, and log file information to: (a) store information so that you will not have to re-enter it during your visit or the next time you visit the TXM.com Sites; (b) provide custom, personalized content and information; (c) monitor the effectiveness of our marketing campaigns; (d) monitor aggregate metrics such as total number of visitors, pages viewed, etc.; and (e) track your entries, submissions, and status in promotions, sweepstakes, and contests. If you download the TXM.com Uploader, your copy of the of the Uploader includes a unique application number. The unique application number and information about your installation of the Uploader (e.g. version number, language) will be sent to TXM.com when the Uploader automatically checks for updates.<br />
          </li></ul>
    </div>

    <div class="dft-hdr grn-bdr">
      Your Choices</div>
      
    <div class="dft-cnt">
          <ul><li>You may, of course, decline to submit personally identifiable information through the TXM.com Sites, in which case you can still view videos and explore the TXM.com Sites, but TXM.com may not be able to provide certain services to you. Some advanced TXM.com features may, for authentication purposes, require you to sign up for other TXM.com services like TXM.com Checkout or AdSense. The privacy notices of those services govern the use of your personal information associated with them.<br />
          </li><li>You may update or correct your personal profile information and email preferences at any time by visiting your account profile page.<br />
          </li><li>You may clear your viewing history at any time through the "Viewing History" feature.<br />
          </li></ul>
      <br />
      Third-party Advertisers, Links to Other Sites<br />
      <br />
      TXM.com allows other companies, called third-party ad servers or ad networks, to serve advertisements within the TXM.com Sites. These third-party ad servers or ad networks use technology to send, directly to your browser, the advertisements and links that appear on the TXM.com Sites. They automatically receive your IP address when this happens. They may also use other technologies (such as cookies, JavaScript, or Web Beacons) to measure the effectiveness of their advertisements and to personalize the advertising content you see.<br />
      <br />
      TXM.com does not provide any personally identifiable information to these third-party ad servers or ad networks without your consent or except as part of a specific program or feature for which you will have the ability to opt-in or opt-out. However, please note that if an advertiser asks TXM.com to show an advertisement to a certain audience (for example, men ages 18-34) or audience segment (for example, men ages 18-24 who have viewed certain channels of content) and you respond to that advertisement, the advertiser or ad-server may conclude that you fit the description of the audience they are trying to reach. The advertiser may also use information regarding your use of the TXM.com Sites, such as the number of times you viewed an ad (but not any personally identifiable information), to determine which ads to deliver to you.<br />
      <br />
      You should consult the respective privacy policies of these third-party ad servers or ad networks (see links below) for more information on their practices and for instructions on how to opt-out of certain practices. TXM.com's privacy policy does not apply to, and we cannot control the activities of, such other advertisers or web sites.<br />
      <br />
      Currently, TXM.com has relationships with the following third-party ad servers or ad networks:<br />
      <br />
         Google, Inc.<br />
         http://www.google.com/privacypolicy.html<br />
    </div>
  </div>
</div>