<div class="row">
    <div class="span4">
        <section class="block">
            <h2>
                Latest Games
            </h2>

            <ul class="media-lineitems">

<?php foreach ($this->newGames as $game): ?>

                <li>
                    <a href="/games/<?php echo $game['id']; ?>/<?php echo Helper_String::toLink($game['title']); ?>/" title="<?php echo $game['title']; ?>">
                        <img src="<?php echo $this->conf->cdn->gameimg; ?><?php echo $game['id']; ?>.gif" alt="<?php echo $game['title']; ?>" />
                        <strong><?php echo $game['title']; ?></strong>
                    </a>
                </li>

<?php endforeach; ?>

            </ul>
        </section>
    </div>

    <div class="span4">
        <section class="block">
            <h2>
                Popular Games
            </h2>

            <ul class="media-lineitems">

<?php foreach ($this->popularGames as $game): ?>

                <li>
                    <a href="/games/<?php echo $game['id']; ?>/<?php echo Helper_String::toLink($game['title']); ?>/" title="<?php echo $game['title']; ?>">
                        <img src="<?php echo $this->conf->cdn->gameimg; ?><?php echo $game['id']; ?>.gif" alt="<?php echo $game['title']; ?>" />
                        <strong><?php echo $game['title']; ?></strong>
                    </a>
                </li>

<?php endforeach; ?>

            </ul>
        </section>
    </div>

    <div class="span4">
        <section class="block">
            <h2>
                Best Games
            </h2>

            <ul class="media-lineitems">

<?php foreach ($this->bestGames as $game): ?>

                <li>
                    <a href="/games/<?php echo $game['id']; ?>/<?php echo Helper_String::toLink($game['title']); ?>/" title="<?php echo $game['title']; ?>">
                        <img src="<?php echo $this->conf->cdn->gameimg; ?><?php echo $game['id']; ?>.gif" alt="<?php echo $game['title']; ?>" />
                        <strong><?php echo $game['title']; ?></strong>
                    </a>
                </li>

<?php endforeach; ?>

            </ul>
        </section>
    </div>
</div>
