<div class="content-block">
    <div class="block-header">
        <a href="/community" title="Return to Community Forums">
            Community
        </a>
        
        &nbsp;&raquo;&nbsp;
        <a href="<?php echo $this->url(array('page' => 1)); ?>" title="<?php echo ($this->forumInfo['page'] != 1 ? 'Return to Page 1 of Forum' : 'Refresh Forum'); ?>">
            <?php echo $this->forumInfo['forumName']; ?>
        </a>

<?php if ($this->forumInfo['page'] != 1): ?>

        &nbsp;&raquo;&nbsp;
        <a href="<?php echo $this->url(); ?>" title="Refresh Page">
            Page <?php echo $this->forumInfo['page']; ?>
        </a>

<?php endif; ?>

    </div>

    <div>
        <table class="data">
            <?php echo $this->sorter; ?>

            <tbody>

<?php foreach ($this->topics as $topic): ?>

                <tr>
                    <td>
                        <a href="/community/topic/<?php echo $topic['id']; ?>" title="<?php echo $topic['title']; ?>">
                            <strong><?php echo $topic['title']; ?></strong>
                        </a>
                    </td>
                    <td>
                        <img src="<?php echo $this->conf->cdn->profile; ?><?php echo $topic['id_user']; ?>.gif" class="text-img" />
                        <a href="<?php echo $topic['author_link_name']; ?>" title="<?php echo $topic['author_nick_name']; ?>">
                            <?php echo $topic['author_nick_name']; ?>
                        </a>
                    </td>
                    <td>
                        <img src="<?php echo $this->conf->cdn->profile; ?><?php echo $topic['reply_user_id']; ?>.gif" class="text-img" />
                        <a href="<?php echo $topic['reply_link_name']; ?>" title="<?php echo $topic['reply_nick_name']; ?>">
                            <?php echo $topic['reply_nick_name']; ?>
                        </a>
                    </td>
                    <td class="text-center"><?php echo $topic['offset']; ?></td>
                    <td class="text-center">-</td>
                    <td class="text-center"><?php echo $topic['popular']; ?></td>
                </tr>

<?php endforeach; ?>
                
            </tbody>
        </table>
    </div>
</div>

<div class="content-block">
    <?php echo $this->paginator; ?>
</div>