<section class="block">
    <div class="h2">
        <a href="/games" title="Return to Games">
            Games
        </a>

        &nbsp;&raquo;&nbsp;
        <a href="" title="<?php echo Helper_String::sanitize($this->gameInfo['title']); ?>">
            <em><?php echo $this->gameInfo['title']; ?></em>
        </a>
    </div>

    <div class="media-box">
        <object type="application/x-shockwave-flash" width="<?php echo $this->gameInfo['width']; ?>" height="<?php echo $this->gameInfo['height']; ?>" data="<?php echo $this->conf->cdn->game; ?><?php echo $this->gameInfo['id']; ?>.swf" style="display: block; margin: auto;">
            <param name="allowAccessScript" value="never" />
            <param name="wmode" value="opaque" />
            <param name="game" value="<?php echo $this->conf->cdn->game; ?><?php echo $this->gameInfo['id']; ?>.swf" />
        </object>
    </div>

    <footer>
        <a href="http://<?php echo $this->gameInfo['link_name']; ?>.<?php echo $this->siteDomain; ?>" title="View Profile" class="text-disabled">
            <img src="<?php echo $this->conf->cdn->profile; ?><?php echo $this->gameInfo['id_user']; ?>.gif" alt="Icon" />
            <?php echo $this->gameInfo['nick_name']; ?>
        </a> on <?php echo $this->gameInfo['date']; ?>
    </footer>
</section>

<div class="row">
    <div class="span4">
        <section class="block">
            <h2>
                Game Details
            </h2>

    <!--        <div id="ratings" class="left" style="margin: 2px 4px;">
                <img src="/games/images/ratings/<?php echo $this->gameInfo['rating']; ?>.gif" alt="Rating <?php echo $this->gameInfo['rating']; ?>" /><br />
                <img src="/games/images/types/<?php echo $this->gameInfo['type']; ?>.gif" alt="Type <?php echo $this->gameInfo['type']; ?>" />
            </div>-->

            <table>
                <tr>
                    <td valign="top">Score:</td>
                    <td valign="top"><strong class="score"><?php echo $this->gameInfo['score']; ?></strong> out of 10.00</td></tr>
                <tr>
                    <td>Status:</td>
                    <td><?php echo $this->gameInfo['votes']; ?> Votes &amp; <?php echo $this->gameInfo['reviews']; ?> Reviews</td></tr>
                <tr>
                    <td>Views:</td>
                    <td><?php echo $this->gameInfo['views']; ?> Plays</td></tr>
                <tr>
                    <td>Website:</td>
                    <td><b><a href="<?php echo $this->gameInfo['web_url']; ?>" title="website"><?php echo $this->gameInfo['web_title']; ?></a></b></td></tr>

            </table>

            <article>
                <?php echo $this->gameInfo['commentary']; ?>
            </article>
        </section>
    </div>

    <div class="span8 linked">
        <section class="block">
            <h2>
                Community Reviews
            </h2>

<?php if ($this->reviews): ?>

<?php foreach ($this->reviews as $count => $review): ?>

<?php if ($count != 0): ?>

        <section class="block">

<?php endif; ?>

            <article>
                <?php echo $review['comment']; ?>
                <?php echo $review['reply']; ?>
            </article>

            <footer>
                <a href="http://<?php echo $review['link_name']; ?>.<?php echo $this->siteDomain; ?>" title="View Profile" class="text-disabled">
                    <img src="<?php echo $this->conf->cdn->profile; ?><?php echo $review['id_user']; ?>.gif" alt="icon" />
                    <?php echo $review['nick_name']; ?>
                </a> on <?php echo $review['date_comment']; ?>
            </footer>
        </section>

<?php endforeach; ?>

<?php else: ?>

        <section class="block">
            <article>
                No comments at this time.
            </article>
        </section>

<?php endif; ?>

    </div>
</div>
