<div class="content-block">
    <div class="block-header">
        Enjoy These Movies &amp; Games!
    </div>

    <div id="txm-index-splash">

<?php foreach ($this->mediaShowcase as $row): ?>

        <a href="/<?php echo $row['type']; ?>/view/<?php echo $row['id']; ?>/<?php echo Helper_String::toLink($row['title']); ?>" title="<?php echo htmlentities($row['title']); ?>"  txm-desc="<?php echo htmlentities($row['synopsis']); ?>">
            <img src="<?php echo $this->conf->cdn->{substr($row['type'], 0, -1) . 'img'}; ?><?php echo $row['id']; ?>.gif" alt="media-<?php echo $row['id']; ?>" />
        </a>

<?php endforeach; ?>

    </div>

    <div id="txm-index-synopsis" class="ui-widget-content ui-corner-all ui-state-hover"></div>
</div>

<div class="left" style="width: 644px; margin-right: 1.333em;">
    <div class="left" style="width: 314px; margin-right: 1.333em;">
        <div class="content-block">
            <div class="block-header">
                Daily Movies
            </div>

            <div class="padding-links index-media">

<?php foreach ($this->mediaMovies as $row): ?>

                <a href="/<?php echo $row['type']; ?>/view/<?php echo $row['id']; ?>/<?php echo Helper_String::toLink($row['title']); ?>" title="<?php echo Helper_String::sanitize($row['title']); ?>">
                    <img src="<?php echo $this->conf->cdn->{substr($row['type'], 0, -1) . 'img'}; ?><?php echo $row['id']; ?>.gif" />
                    <span>
                        <strong><?php echo Helper_String::sanitize($row['title']); ?></strong><br />
                        <?php echo Helper_String::sanitize($row['synopsis']); ?>
                    </span>
                </a>

<?php endforeach; ?>

            </div>
        </div>
    </div>

    <div class="left" style="width: 314px;">
        <div class="content-block">
            <div class="block-header">
                Daily Games
            </div>

            <div class="padding-links index-media">

<?php foreach ($this->mediaGames as $row): ?>

                <a href="/<?php echo $row['type']; ?>/view/<?php echo $row['id']; ?>/<?php echo Helper_String::toLink($row['title']); ?>" title="<?php echo Helper_String::sanitize($row['title']); ?>">
                    <img src="<?php echo $this->conf->cdn->{substr($row['type'], 0, -1) . 'img'}; ?><?php echo $row['id']; ?>.gif" />
                    <span>
                        <strong><?php echo Helper_String::sanitize($row['title']); ?></strong><br />
                        <?php echo Helper_String::sanitize($row['synopsis']); ?>
                    </span>
                </a>

<?php endforeach; ?>

            </div>
        </div>
    </div>
    <div class="clr"></div>

<?php foreach ($this->dailyNews as $row): ?>

    <div class="content-block">
        <a class="block-header" href="community/topic/<?php echo $row['id']; ?>/<?php echo $row['title_link']; ?>/" title="Read Article">
            <?php echo $row['title']; ?>
        </a>

        <div class="padding-content">
            <?php echo $row['post']; ?>
        </div>

        <div class="padding-content" style="width: auto; overflow: hidden; border-top: 1px solid #ddd;">
            <div class="left text-disabled">
                <a href="http://<?php echo $row['link_name']; ?>.<?php echo $this->siteDomain; ?>" title="View Profile">
                    <img src="<?php echo $this->conf->cdn->profile; ?><?php echo $row['id_user']; ?>.gif" alt="Icon" class="text-img" />
                </a>

                <a href="http://<?php echo $row['link_name']; ?>.<?php echo $this->siteDomain; ?>" title="View Profile" ><?php echo $row['nick_name']; ?></a> on <?php echo $row['date']; ?>
            </div>

            <div style="text-align: right;">
                <?php echo $row['views']; ?> Views &nbsp;|&nbsp;
                <a href="community/topic/<?php echo $row['id']; ?>/<?php echo $row['title_link']; ?>/" title="Read <?php echo $row['replies']; ?> Comments">
                    <?php echo $row['replies']; ?> Comments
                </a>
            </div>
        </div>
    </div>

<?php endforeach; ?>

</div>

<div class="left" style="width: 300px;">

    <div class="content-block">
        <div class="block-header">
            What We Are About
        </div>

        <div class="padding-content">
            TXM.com <em>is</em> movies and games, created by people from across the Internet. It is a
            community of artists, developers, and fans.
            <br /><br />

            It pushes the next generation of creators into the spotlight of animated
            <a href="/movies" title="Watch Movies">Movies</a> and
            <a href="/games" title="Play Games">Games</a> as it strives to have the most diverse
            <a href="/community" title="Engage Community">Community</a>
            with the help of loyal and caring fans.
            <br /><br />

            TXM.com encourages an environment of fair critiques and ample voting
            to give creators the best feedback for constant improvement.
<!--            <br /><br />

            <a href="/createaccount" title="Create Account">Create an Account</a> to become engaged!-->
        </div>
    </div>

    <div class="content-block">
        <div class="block-header">
            More News Posts
        </div>

        <div class="padding-links">

<?php foreach ($this->sidebarNews as $row): ?>

            <a href="/forums/threads/<?php echo $row['id']; ?>/<?php echo Helper_String::toLink($row['title_link']); ?>" title="<?php echo htmlentities($row['title']); ?>">
                <img src="<?php echo $this->conf->cdn->profile; ?><?php echo $row['id_user']; ?>.gif" alt="Icon" class="text-img" />
                <?php echo $row['title']; ?></a>

<?php endforeach; ?>

        </div>
    </div>

    <div class="content-block">
        <div class="block-header">
            Sponsored Partnerships
        </div>

        <div class="padding-links">
            <a href="http://www.youtube.com/lorenandtxm" title="Austin Based Film and Animation Studio" target="_blank">Loren Productions (Short Films)</a>
            <a href="http://www.diverge.ws/" title="Multiplayer Online Flash Games" target="_blank">Diverge Creations (Online Games)</a>
            <a href="http://gamemusic4all.blogspot.com/" title="Promotion of Gaming Music" target="_blank">Game Music 4 All (Music Promoter)</a>
            <a href="http://www.shamoozal.com/" title="Episodic Rabbit Cartoon" target="_blank">Shamoozal (Episodic Comedy)</a>
            <a href="http://www.razoric.com/" target="_blank">Razoric</a>
            <a href="http://www.psychogoldfish.com/" target="_blank">Psycho Goldfish</a>
            <a href="http://www.revivaleyes.com/" target="_blank">Revival Eyes</a>
        </div>
    </div>

    <div class="content-block">
        <div class="block-header">
            Additional Flash Portals
        </div>

        <div class="padding-links">
            <a href="http://www.newgrounds.com/" title="Flash Movies &amp; Games" target="_blank">Newgrounds (Forefather of Flash)</a>
            <a href="http://www.flashportal.com/" title="Manul Flash Uploads" target="_blank">Flash Portal (Manual Flash Portal)</a>
        </div>
    </div>
</div>

<div class="clr"></div>
