<thead>
    <tr>

<?php foreach ($this->sortList as $key => $sort): ?>

        <th>
            <a href="<?php echo $sort[3]; ?>" title="Sort by <?php echo ($sort[2] == 'd' ? 'Descending' : 'Ascending'); ?> <?php echo $sort[1]; ?>">
                <?php echo $sort[1]; ?>
                <sup><?php echo (isset($sort[4]) ? ($sort[2] == 'd' ? ' &and;' : ' &or;') : ''); ?></sup>
            </a>
        </th>

<?php endforeach; ?>

    </tr>
</thead>