<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta charset="utf-8">

        <meta name="title"       content="<?php echo Helper_String::sanitize(strip_tags($this->headTitle())); ?>" />
        <meta name="description" content="<?php echo Helper_String::sanitize(strip_tags($this->headTitle())); ?>" />
        <meta name="owner"       content="support@txm.com" />
        <meta name="keywords"    content="flash, movies, juegos, games, portal, independent, film, community, txmafia, newgrounds, videogamedc, flashportal, minijuegos, sprites, nintendo, mario, adult, snipers, revenge, entertainment" />

        <meta name="google-site-verification" content="mjtAqwSzRwOdJWXP2-aetq691wz3i0v6oyimexkJUgA" />

        <?php echo $this->headTitle(); ?>

        <?php echo $this->headLink(); ?>

        <?php echo $this->headStyle(); ?>

        <?php echo $this->headScript(); ?>
    </head>

    <body>
        <!--<div id="tweet-container" class="ui-widget ui-state-error" style="padding: 1.333em; text-align: center; border-top: none; border-left: none; border-right: none;">
            <span class="ui-icon ui-icon-alert" style="display: inline-block; vertical-align: text-bottom;"></span>
            <strong>Latest Update</strong>: <span id="tweet-content"></span>
            <a href="http://twitter.com/txmdotcom" title="Follow TXM on TWitter" target="_blank" class="ui-state-error-text" style="font-style: italic; opacity: 0.5;">Follow Updates</a>
        </div>-->

        <div id="page">
            <header id="header">
                <a href="<?php echo $this->siteLevel; ?>" title="TXM.com" id="logo">
                    <h1>
                        TXM<span>.com</span>
                    </h1>
                </a>

                <div class="googlead">
                    <script type="text/javascript"><!--
                        google_ad_client = "ca-pub-7413795255296720";
                        /* TXM.com */
                        google_ad_slot = "5275619564";
                        google_ad_width = 468;
                        google_ad_height = 60;
                    //-->
                    </script>
                    <script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
                </div>

                <div id="user">

<?php if ($this->siteUser): ?>

                    <span>
                        <a href="<?php echo $this->siteUser['linkName']; ?>" title="View Your Account">
                            <?php echo $this->siteUser['nickName']; ?>
                        </a>
                    </span><span>
                        <a href="<?php echo $this->siteLevel; ?>account/signout" title="Sign Out">
                            Sign Out
                        </a>
                    </span>

<?php elseif (0): ?>

                    <a href="/create-account" title="Create An Account">
                        Create An Account
                    </a><a href="/sign-in" title="Sign In">
                        Sign In
                    </a>

<?php endif; ?>

                </div>

                <nav>
                    <ul>
                        <li>
                            <a href="<?php echo $this->siteLevel; ?>movies" title="Watch Movies">MOVIES</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->siteLevel; ?>games" title="Play Games">GAMES</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->siteLevel; ?>community" title="Engage Community">COMMUNITY</a>
                        </li>
                        <li><a href="#">&nbsp;</a></li>
                    </ul>
                </nav>
            </header>

            <div id="content">

                <?php echo $this->layout()->content; ?>

            </div>
        </div>

        <footer id="footer">
            <section>
                <nav></nav>
                <small>
                    Copyright &copy; <?php echo date('Y'); ?> <a href="http://drd.io/" title="DRD.IO | Austin Web Development">DRD.IO Inc.</a> &nbsp;|&nbsp;
                    Designed by <a href="http://kevinnuut.com/" title="NUUT.co | Art, Fashion, Gaming, and Design">NUUT.co</a> &nbsp;|&nbsp;
                    <a href="<?php echo $this->siteLevel; ?>help/terms" title="Terms of Service">Terms of Service</a>
                </small>
            </section>
        </footer>


        <!-- Google -->
        <script src="http://www.google-analytics.com/ga.js" type="text/javascript"></script>
        <script type="text/javascript">var pageTracker=_gat._getTracker("UA-723316-1");pageTracker._initData();pageTracker._trackPageview();</script>
    </body>
</html>
