<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta charset="utf-8">

        <meta name="title"       content="<?php echo Helper_String::sanitize(strip_tags($this->headTitle())); ?>" />
        <meta name="description" content="<?php echo Helper_String::sanitize(strip_tags($this->headTitle())); ?>" />
        <meta name="owner"       content="support@txm.com" />
        <meta name="keywords"    content="flash, movies, juegos, games, portal, independent, film, community, txmafia, newgrounds, videogamedc, flashportal, minijuegos, sprites, nintendo, mario, adult, snipers, revenge, entertainment" />

        <meta name="google-site-verification" content="mjtAqwSzRwOdJWXP2-aetq691wz3i0v6oyimexkJUgA" />
        
        <?php echo $this->headTitle(); ?>

        <?php echo $this->headLink(); ?>

        <?php echo $this->headStyle(); ?>
        
        <?php echo $this->headScript(); ?>
    </head>

    <body>
        <!--<div id="tweet-container" class="ui-widget ui-state-error" style="padding: 1.333em; text-align: center; border-top: none; border-left: none; border-right: none;">
            <span class="ui-icon ui-icon-alert" style="display: inline-block; vertical-align: text-bottom;"></span>
            <strong>Latest Update</strong>: <span id="tweet-content"></span>
            <a href="http://twitter.com/txmdotcom" title="Follow TXM on TWitter" target="_blank" class="ui-state-error-text" style="font-style: italic; opacity: 0.5;">Follow Updates</a>
        </div>-->

        <div id="page">
            <div id="header">
                <a href="<?php echo $this->siteLevel; ?>" title="TXM.com" id="header-logo">
                    TXM<span>.com</span>
                </a>

                <div id="header-status">

<?php if ($this->siteUser): ?>

                    <span>
                        <a href="<?php echo $this->siteUser['linkName']; ?>" title="View Your Account">
                            <?php echo $this->siteUser['nickName']; ?>
                        </a>
                    </span><span>
                        <a href="<?php echo $this->siteLevel; ?>account/signout" title="Sign Out">
                            Sign Out
                        </a>
                    </span>

<?php else: ?>

<!--                    <span>
                        <a id="site-sign-in" href="<?php echo $this->siteLevel; ?>account/signin" title="Sign In to Your Account">
                            Sign In
                        </a>
                    </span><span>
                        <a href="<?php echo $this->siteLevel; ?>account/create" title="Create an Account &amp; Join the Fun!">
                            <strong>Create Account</strong>
                        </a>
                    </span>-->

<?php endif; ?>
                
                </div>

                <div id="header-navigation">
                    <ul>
                        <li>
                            <a href="<?php echo $this->siteLevel; ?>movies" title="Watch Movies">MOVIES</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->siteLevel; ?>games" title="Play Games">GAMES</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->siteLevel; ?>community" title="Engage Community">COMMUNITY</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div id="content">

                <?php echo $this->layout()->content; ?>

            </div>

            <div id="footer">
                Copyright &copy; <?php echo date('Y'); ?> <a href="http://dierobotdie.com/" title="Austin Web Development">DieRobotDie, LLC</a> &nbsp;|&nbsp;
                Designed by <a href="http://kevinnuut.com/" title="Art, Fashion and Architecture">KevinNuut.com</a> &nbsp;|&nbsp;
                <a href="<?php echo $this->siteLevel; ?>help/terms" title="Terms of Service">Terms of Service</a>
            </div>
        </div>

        <div></div>
        
        <!-- Google -->
        <script src="http://www.google-analytics.com/ga.js" type="text/javascript"></script>
        <script type="text/javascript">var pageTracker=_gat._getTracker("UA-723316-1");pageTracker._initData();pageTracker._trackPageview();</script>
    </body>
</html>